apiVersion: core.federation.k8s.io/v1alpha1
kind: FederationConfig
metadata:
  name: federation-v2
spec:
  limited-scope: "false"
  registry-namespace: federation-system
  controller-duration:
    available-delay: "20s"
    unavailable-delay: "60s"
    cluster-monitor-period: "40s"
  leader-elect:
    lease-duration: "15s"
    renew-deadline: "10s"
    retry-period: "5s"
    resource-lock: configmaps
  feature-gates:
  - name: push-reconciler
    enabled: true
  - name: scheduler-preferences
    enabled: true
  - name: cross-cluster-service-discovery
    enabled: true
  - name: federated-ingress
    enabled: true

