language: go

go:
  - "1.10.1"

sudo: required

services:
  - docker

# Install must be set to prevent default `go get` to run.
# The dependencies have already been vendored by `dep` so
# we don't need to fetch them.
install:
  -

script:
  - ./scripts/pre-commit.sh
  - vendor/github.com/kubernetes/repo-infra/verify/verify-boilerplate.sh -- rootdir="$GOPATH/src/github.com/kubernetes-sigs/federation-v2" -v
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/imagebuild.sh
  on:
    repo: kubernetes-sigs/federation-v2
    all_branches: true


# TBD. Suppressing for now.
notifications:
  email: false
