apiVersion: core.kubefed.k8s.io/v1alpha1
kind: KubefedConfig
metadata:
  name: kubefed
  namespace: {{ .Release.Namespace }}
spec:
  scope: {{ .Values.global.scope | default "Cluster" | quote }}
  controllerDuration:
    availableDelay: {{ .Values.clusterAvailableDelay | default "20s" | quote }}
    unavailableDelay: {{ .Values.clusterUnavailableDelay | default "60s" | quote }}
  leaderElect:
    leaseDuration: {{ .Values.leaderElectLeaseDuration | default "15s" | quote }}
    renewDeadline: {{ .Values.leaderElectRenewDeadline | default "10s" | quote }}
    retryPeriod: {{ .Values.leaderElectRetryPeriod | default "5s" | quote }}
    resourceLock: {{ .Values.leaderElectResourceLock | default "configmaps" | quote }}
  clusterHealthCheck:
    periodSeconds: {{ .Values.clusterHealthCheckPeriodSeconds | default 10 }}
    failureThreshold: {{ .Values.clusterHealthCheckFailureThreshold | default 3 }}
    successThreshold: {{ .Values.clusterHealthCheckSuccessThreshold | default 1 }}
    timeoutSeconds: {{ .Values.clusterHealthCheckTimeoutSeconds | default 3 }}
  syncController:
    skipAdoptingResources: {{ .Values.syncController.skipAdoptingResources | default false }}
  featureGates:
{{- if .Values.featureGates }}
  - name: PushReconciler
    enabled: {{ .Values.featureGates.PushReconciler | default true }}
  - name: SchedulerPreferences
    enabled: {{ .Values.featureGates.SchedulerPreferences | default true }}
  - name: CrossClusterServiceDiscovery
    enabled: {{ .Values.featureGates.CrossClusterServiceDiscovery | default true }}
  - name: FederatedIngress
    enabled: {{ .Values.featureGates.FederatedIngress | default true }}
{{- end }}
