apiVersion: core.kubefed.k8s.io/v1alpha1
kind: KubefedConfig
metadata:
  name: kubefed
  namespace: kube-federation-system
spec:
  leader-elect:
    lease-duration: 1500ms
    renew-deadline: 1000ms
    retry-period: 500ms
