apiVersion: core.kubefed.k8s.io/v1alpha1
kind: KubefedConfig
metadata:
  name: kubefed
  namespace: kube-federation-system
spec:
  leaderElect:
    leaseDuration: 1500ms
    renewDeadline: 1000ms
    retryPeriod: 500ms
