name: Push

on:
  push:
    tags:
      - "v*"
    branches:
      - "master"

jobs:
  test-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.5'
      - name: Docker push
        run: |
          ./hack/verify-docfiles.sh && echo "Skipping build - only doc files have changed!" || \
            make push
