name: Test and Push

on:
  push:
    tags:
      - "v*"
    branches:
      - "master"

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.5'
      
      - name: Run tests
        run: DOWNLOAD_BINARIES=y bash -x ./scripts/pre-commit.sh

      - name: Push Docker images
        run: make push
