apiVersion: types.kubefed.k8s.io/v1alpha1
kind: KubefedClusterRole
metadata:
  name: test-clusterrole
spec:
  template:
    rules:
    - apiGroups:
      - '*'
      resources:
      - '*'
      verbs:
      - '*'
  placement:
    clusters:
    - name: cluster2
    - name: cluster1
